### ISSUE TITLE
make unique an option for the whole tree

### ISSUE THREAD

**Issue by youkaichao** [andylamp/BPlusTree#2] opened 2019-05-03 06:22 UTC
I think whether a tree is `unique` or not. But currently, I find that in every insertion we can choose to be `unique` or not. This is not a common choice.

**Comment by andylamp** [comment] 2019-05-03 11:56
Actually what you are saying describes two completely different data structures - `unique` in this project means that the data-structure created in each instance can allow duplicate keys or not. It's also one of the most commonly used options and a very common occurrence. Further, the functionality you are asking is not directly implemented but can be easily done by probing each (K, V) pair from two trees and see if they all match.

hope this helps...

edit: since this is not a bug rather than a feature request for now am closing the issue unless you want to implement it; if you do feel free to make a PR and reopen the issue.

**Closed as completed** 2019-05-03 12:01 UTC
